// <auto-generated />
using System;
using IkiForma.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IkiForma.Data.Migrations
{
    [DbContext(typeof(IkiFormaDbContext))]
    [Migration("20260916143330_AddStintTrackingFields")]
    partial class AddStintTrackingFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IkiForma.Data.Entities.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.Property<string>("WikidataId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("wikidata_id");

                    b.HasKey("Id")
                        .HasName("pk_league");

                    b.HasIndex("SportId")
                        .HasDatabaseName("ix_league_sport_id");

                    b.HasIndex("WikidataId")
                        .IsUnique()
                        .HasDatabaseName("ix_league_wikidata_id");

                    b.ToTable("league", (string)null);
                });

            modelBuilder.Entity("IkiForma.Data.Entities.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("birth_date");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("WikidataId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("wikidata_id");

                    b.HasKey("Id")
                        .HasName("pk_player");

                    b.HasIndex("WikidataId")
                        .IsUnique()
                        .HasDatabaseName("ix_player_wikidata_id");

                    b.ToTable("player", (string)null);
                });

            modelBuilder.Entity("IkiForma.Data.Entities.Sport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_sport");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_sport_code");

                    b.ToTable("sport", (string)null);
                });

            modelBuilder.Entity("IkiForma.Data.Entities.Stint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Appearances")
                        .HasColumnType("integer")
                        .HasColumnName("appearances");

                    b.Property<DateOnly?>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<string>("EndDatePrecision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("end_date_precision");

                    b.Property<int?>("Goals")
                        .HasColumnType("integer")
                        .HasColumnName("goals");

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer")
                        .HasColumnName("player_id");

                    b.Property<string>("SourceStatementId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("source_statement_id");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("StartDatePrecision")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("start_date_precision");

                    b.Property<string>("StintType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("stint_type");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_stint");

                    b.HasIndex("PlayerId")
                        .HasDatabaseName("ix_stint_player_id");

                    b.HasIndex("SourceStatementId")
                        .IsUnique()
                        .HasDatabaseName("ix_stint_source_statement_id");

                    b.HasIndex("TeamId", "PlayerId")
                        .HasDatabaseName("ix_stint_team_id_player_id");

                    b.ToTable("stint", (string)null);
                });

            modelBuilder.Entity("IkiForma.Data.Entities.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("integer")
                        .HasColumnName("league_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<int>("SportId")
                        .HasColumnType("integer")
                        .HasColumnName("sport_id");

                    b.Property<string>("WikidataId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("wikidata_id");

                    b.HasKey("Id")
                        .HasName("pk_team");

                    b.HasIndex("LeagueId")
                        .HasDatabaseName("ix_team_league_id");

                    b.HasIndex("SportId")
                        .HasDatabaseName("ix_team_sport_id");

                    b.HasIndex("WikidataId")
                        .IsUnique()
                        .HasDatabaseName("ix_team_wikidata_id");

                    b.ToTable("team", (string)null);
                });

            modelBuilder.Entity("IkiForma.Data.Entities.League", b =>
                {
                    b.HasOne("IkiForma.Data.Entities.Sport", "Sport")
                        .WithMany("Leagues")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_league_sports_sport_id");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("IkiForma.Data.Entities.Stint", b =>
                {
                    b.HasOne("IkiForma.Data.Entities.Player", "Player")
                        .WithMany("Stints")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stint_player_player_id");

                    b.HasOne("IkiForma.Data.Entities.Team", "Team")
                        .WithMany("Stints")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stint_teams_team_id");

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("IkiForma.Data.Entities.Team", b =>
                {
                    b.HasOne("IkiForma.Data.Entities.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_team_league_league_id");

                    b.HasOne("IkiForma.Data.Entities.Sport", "Sport")
                        .WithMany("Teams")
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_team_sport_sport_id");

                    b.Navigation("League");

                    b.Navigation("Sport");
                });

            modelBuilder.Entity("IkiForma.Data.Entities.League", b =>
                {
                    b.Navigation("Teams");
                });

            modelBuilder.Entity("IkiForma.Data.Entities.Player", b =>
                {
                    b.Navigation("Stints");
                });

            modelBuilder.Entity("IkiForma.Data.Entities.Sport", b =>
                {
                    b.Navigation("Leagues");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("IkiForma.Data.Entities.Team", b =>
                {
                    b.Navigation("Stints");
                });
#pragma warning restore 612, 618
        }
    }
}
